
/* Generated by Interface Builder */

#import "Channel.h"
#import <AppKit/AppKit.h>

@implementation Channel:NSObject


+ (void)initialize
{
  if (self == [Channel class])
  {
      (void)[Channel setVersion: 0];	/* class version, see read: */
  }
  return;
}


/* */

- init
{
  [super init];
  flag = 0;
  level = 1.0;
  pan = 0.5;
  reverb = 0.2;
  chorus = 0.0;
  vibrato = 0.05;
  return self;
}



- (id)initWithCoder:(NSCoder *)aDecoder
{
  int v;
//  [super initWithCoder:aDecoder]; //sb: unnec
  v = [aDecoder versionForClassName:@"Channel"];
  if (v == 0)
  {
    [aDecoder decodeValuesOfObjCTypes:"fffff", &level, &pan, &reverb, &chorus, &vibrato];
  }
  return self;
}


- (void)encodeWithCoder:(NSCoder *)aCoder
{
//    [super encodeWithCoder:aCoder]; //sb: unnec
    [aCoder encodeValuesOfObjCTypes:"fffff", &level, &pan, &reverb, &chorus, &vibrato];
}

- (void)encodeWithPropertyListCoder:(OAPropertyListCoder *)aCoder
{
    [aCoder setFloat:level forKey:@"level"];
    [aCoder setFloat:pan forKey:@"pan"];
    [aCoder setFloat:reverb forKey:@"reverb"];
    [aCoder setFloat:chorus forKey:@"chorus"];
    [aCoder setFloat:vibrato forKey:@"vibrato"];
}


@end
