/*
  Character codes and classes
*/

#import "mux.h"

/* modified for NeXTStupid Encoding */

unsigned short charclass[256] =
{
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
/*  SP */ CHFIGURE,
/*  !  */ CHPUNCT | CHACCID | CHACOUT | CHFIGURE,
/*  "  */ 0,
/*  #  */ CHACCID | CHACOUT | CHFIGURE,
/*  $  */ 0,
/*  %  */ 0,
/*  &  */ CHALFAB,
/*  '  */ 0,
/*  (  */ CHOPBRA | CHFIGURE,
/*  )  */ CHEDBRA | CHFIGURE,
/*  *  */ 0,
/*  +  */ CHALFAB | CHFIGURE,
/*  ,  */ CHPUNCT,
/*  -  */ 0,
/*  .  */ CHPUNCT,
/*  /  */  CHFIGURE,
/*  0  */ CHDIGIT | CHFIGURE,
/*  1  */ CHDIGIT | CHFIGURE,
/*  2  */ CHDIGIT | CHFIGURE,
/*  3  */ CHDIGIT | CHFIGURE,
/*  4  */ CHDIGIT | CHFIGURE,
/*  5  */ CHDIGIT | CHFIGURE,
/*  6  */ CHDIGIT | CHFIGURE,
/*  7  */ CHDIGIT | CHFIGURE,
/*  8  */ CHDIGIT | CHFIGURE,
/*  9  */ CHDIGIT | CHFIGURE,
/*  :  */ 0,
/*  ;  */ 0,
/*  <  */ CHOPBRA | CHFIGURE,
/*  =  */ 0,
/*  >  */ CHEDBRA | CHACOUT | CHFIGURE,
/*  ?  */ CHPUNCT | CHALFAB,
/*  @  */ CHACCID | CHACOUT | CHFIGURE,
/*  A  */ CHVOWEL | CHALFAB,
/*  B  */ CHALFAB,
/*  C  */ CHALFAB,
/*  D  */ CHALFAB,
/*  E  */ CHVOWEL | CHALFAB,
/*  F  */ CHALFAB | CHACOUT,
/*  G  */ CHALFAB,
/*  H  */ CHALFAB,
/*  I  */ CHVOWEL | CHALFAB,
/*  J  */ CHALFAB,
/*  K  */ CHALFAB,
/*  L  */ CHALFAB,
/*  M  */ CHALFAB,
/*  N  */ CHALFAB,
/*  O  */ CHVOWEL | CHALFAB | CHEDBRA,
/*  P  */ CHALFAB,
/*  Q  */ CHALFAB,
/*  R  */ CHALFAB,
/*  S  */ CHALFAB,
/*  T  */ CHALFAB,
/*  U  */ CHVOWEL | CHALFAB,
/*  V  */ CHALFAB | CHACOUT,
/*  W  */ 0,
/*  X  */ CHALFAB,
/*  Y  */ CHALFAB | CHVOWEL,
/*  Z  */ CHALFAB,
/*  [  */ CHOPBRA | CHFIGURE,
/*  \  */ 0,
/*  ]  */ CHEDBRA | CHFIGURE,
/*  ^  */ 0,
/*  _  */ 0,
/*  `  */ 0,
/*  a  */ CHVOWEL | CHTABLE,
/*  b  */ CHTABLE,
/*  c  */ CHTABLE,
/*  d  */ CHTABLE | CHACOUT,
/*  e  */ CHVOWEL | CHTABLE | CHEDBRA,
/*  f  */ CHTABLE,
/*  g  */ CHTABLE,
/*  h  */ CHTABLE,
/*  i  */ CHVOWEL | CHTABLE,
/*  j  */ CHTABLE,
/*  k  */ CHTABLE,
/*  l  */ CHTABLE,
/*  m  */ CHTABLE | CHACOUT,
/*  n  */ CHTABLE | CHACOUT,
/*  o  */ CHVOWEL | CHTABLE| CHEDBRA,
/*  p  */ CHTABLE,
/*  q  */ CHTABLE,
/*  r  */ 0,
/*  s  */ 0,
/*  t  */ 0,
/*  u  */ CHVOWEL | CHACOUT,
/*  v  */ CHACOUT,
/*  w  */ 0,
/*  x  */ 0,
/*  y  */ CHVOWEL,
/*  z  */ 0,
/*  {  */ CHOPBRA | CHFIGURE,
/*  |  */ 0,
/*  }  */ CHEDBRA | CHFIGURE,
/*  ~  */ 0,
0,
/* Agr */ CHVOWEL,
/* Aac */ CHVOWEL,
/* Aci */ CHVOWEL,
/* Ati */ CHVOWEL,
/* Adi */ CHVOWEL,
/* Ari */ CHVOWEL,
/* Cce */ 0,
/* Egr */ CHVOWEL,
/* Eac */ CHVOWEL,
/* Eci */ CHVOWEL,
/* Edi */ CHVOWEL,
/* Igr */ CHVOWEL,
/* Iac */ CHVOWEL,
/* Ici */ CHVOWEL,
/* Idi */ CHVOWEL,
/* -D  */ 0,
/* Nti */ 0,
/* Ogr */ CHVOWEL,
/* Oac */ CHVOWEL,
/* Oci */ CHVOWEL,
/* Oti */ CHVOWEL,
/* Odi */ CHVOWEL,
/* Ugr */ CHVOWEL,
/* Uac */ CHVOWEL,
/* Uci */ CHVOWEL,
/* Udi */ CHVOWEL,
/* Yac */ CHVOWEL,
0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0,
/* agr */ CHVOWEL,
/* aac */ CHVOWEL,
/* aci */ CHVOWEL,
/* ati */ CHVOWEL,
/* adi */ CHVOWEL,
/* ari */ CHVOWEL,
/* cci */ 0,
/* egr */ CHVOWEL,
/* eac */ CHVOWEL,
/* eci */ CHVOWEL,
/* edi */ CHVOWEL,
/* igr */ CHVOWEL,
/* AE  */ CHVOWEL,
/* iac */ CHVOWEL,
/* -a  */ 0,
/* ici */ CHVOWEL,
/* idi */ CHVOWEL,
/* -d  */ 0,
/* nti */ 0,
0, CHVOWEL, CHVOWEL, 0,
/* ogr */ CHVOWEL,
/* oac */ CHVOWEL,
/* oci */ CHVOWEL,
/* oti */ CHVOWEL,
/* odi */ CHVOWEL,
/* ae */  CHVOWEL,
/* ugr */ CHVOWEL,
/* uac */ CHVOWEL,
/* uci */ CHVOWEL,
/* i-. */ CHVOWEL,
/* udi */ CHVOWEL,
/* yac */ CHVOWEL,
/*  l-  */ 0,
CHVOWEL, CHVOWEL, 0, 0,
/* ydi */ CHVOWEL,
0, 0
};
